Use paunch for compute during issu
Change-Id: Ia950fc03a94159054e280f48e7a429b9e9d8cce3
Partial-Bug: #1801956

diff --git a/templates/contrail/issu_compute_deploy.sh.erb b/templates/contrail/issu_compute_deploy.sh.erb
--- a/templates/contrail/issu_compute_deploy.sh.erb
+++ b/templates/contrail/issu_compute_deploy.sh.erb
@@ -24,41 +24,6 @@ if [[ "${is_dpdk,,}" == 'true' ]] ; then
   dpdk_opts='--dpdk_enabled'
 fi
 
-container_registry=${container_registry:-<%= @container_registry %>}
-container_tag=${container_tag:-<%= @container_tag %>}
-ansible_deployer_image=${ansible_deployer_image:-"${container_registry}/contrail-kolla-ansible-deployer:${container_tag}"}
-
-host_home_dir=~
-host_ssh_dir=${host_ssh_dir:-"$host_home_dir/.ssh"}
-
-instances_yaml=${instances_yaml:-'<%= @instances_yaml_file_name %>'}
-working_dir=${working_dir:-'/tmp/contrail_issu'}
-mkdir -p "$working_dir"
-
-cp -f "$instances_yaml" "${working_dir}/instances.yaml"
-
-cat << EOF > ${working_dir}/container_hosts.yml
-ansible_python_interpreter: /opt/rh/python27/root/usr/bin/python2.7
-contrail_ansible_environment:
-  PATH: /opt/rh/python27/root/usr/bin:{{ lookup( 'env', 'PATH') }}
-  LD_LIBRARY_PATH: /opt/rh/python27/root/usr/lib64
-  PYTHONPATH: "{{ lookup( 'env', 'PYTHONPATH') }}:/usr/lib64/python2.7/site-packages"
-EOF
-
-cat << EOF > ${working_dir}/entrypoint.sh
-#!/bin/bash -x
-mkdir -p ~/.ssh
-chmod 700 ~/.ssh
-cp $working_dir/ssh/* ~/.ssh/
-chown -R root:root ~/.ssh
-cd /root/contrail-ansible-deployer;
-cp -f ${working_dir}/instances.yaml config/
-mkdir -p inventory/group_vars
-cp -f ${working_dir}/container_hosts.yml inventory/group_vars/container_hosts.yml
-ansible-playbook -v -e orchestrator=openstack -i inventory/ playbooks/install_contrail.yml
-EOF
-chmod +x ${working_dir}/entrypoint.sh
-
 sudo systemctl stop supervisor-vrouter
 sudo systemctl disable supervisor-vrouter
 
@@ -85,13 +50,39 @@ if [[ "$old_name" != "$new_name" ]] ; then
   provision_vrouter $new_name add
 fi
 
-sudo docker run --rm -it --network host --name issu_deploy \
-  -v "$working_dir":"$working_dir" \
-  -v "$host_ssh_dir":"$working_dir/ssh":ro \
-  --entrypoint ${working_dir}/entrypoint.sh \
-  $ansible_deployer_image
+# remove old vrouter
+sudo yum remove -y contrail-vrouter
+# remove old links after removal rpm 
+sudo find /lib/modules/ -name vrouter.ko -type l -exec rm -f {} +
 
-if [[ $? != 0 ]] ; then
-  echo "ERROR: failed to run deploy issu Contrail Controller node"
-  exit -1
-fi
+function run_step(){
+  local step=$1
+  local config_file="/var/lib/tripleo-config/hashed-docker-container-startup-config-step_${step}.json"
+  sudo paunch --debug apply --managed-by tripleo \
+    --config-id tripleo_step${step} \
+    --file $config_file
+
+  if [[ $? != 0 ]] ; then
+    echo "ERROR: failed to run step $step"
+    return 1
+  fi
+
+  local compact_config_file="/var/lib/tripleo-config/docker-container-startup-config-step_${step}.json"
+  sudo bash -c "cat $$config_file | jq -c '.' > $compact_config_file"
+  sudo chmod 600 $compact_config_file
+}
+
+for i in 1 2 3 ; do
+  run_step $i || exit -1
+done
+
+# update modules dependencies
+sudo depmod -a
+
+run_step 5 || exit -1
+
+echo "ISSU node deployed successfully"
+echo "Wait Contrail is initializing..." 
+sleep 10
+echo "Contrail status:"
+sudo contrail-status
